<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Idea;
use App\Models\TeamMember;
use Illuminate\Support\Str;

class IdeaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $ideas = [
            [
                'idea_title' => 'Smart Water Meter',
                'slug' => Str::slug('Smart Water Meter-' . Str::random(4)),
                'thematic_area_id' => 1,
                'abstract' => 'A device to monitor water usage in real time.',
                'problem_statement' => 'Water wastage due to lack of monitoring.',
                'proposed_solution' => 'Install smart meters to track usage.',
                'cost_benefit_analysis' => 'Reduces wastage, saves money.',
                'declaration_of_interests' => 'None',
                'original_idea_disclaimer' => true,
                'collaboration_enabled' => true,
                'team_effort' => true,
                'current_revision_number' => 1,
                'collaboration_deadline' => now()->addMonth(),
                'status' => 'draft',
                'attachment' => null,
                'attachment_filename' => null,
                'attachment_mime' => null,
                'attachment_size' => null,
                'user_id' => rand(1, 5),
            ],
            [
                'idea_title' => 'Solar-Powered Charger',
                'slug' => Str::slug('Solar-Powered Charger-' . Str::random(4)),
                'thematic_area_id' => 2,
                'abstract' => 'Portable charger using solar energy.',
                'problem_statement' => 'Limited access to electricity in rural areas.',
                'proposed_solution' => 'Develop affordable solar chargers.',
                'cost_benefit_analysis' => 'Promotes green energy.',
                'declaration_of_interests' => 'None',
                'original_idea_disclaimer' => false,
                'collaboration_enabled' => false,
                'team_effort' => false,
                'current_revision_number' => 1,
                'collaboration_deadline' => null,
                'status' => 'draft',
                'attachment' => null,
                'attachment_filename' => null,
                'attachment_mime' => null,
                'attachment_size' => null,
                'user_id' => rand(1, 5),
            ],
            [
                'idea_title' => 'Community Recycling App',
                'slug' => Str::slug('Community Recycling App-' . Str::random(4)),
                'thematic_area_id' => 3,
                'abstract' => 'App to coordinate recycling efforts.',
                'problem_statement' => 'Low recycling rates in urban areas.',
                'proposed_solution' => 'Mobile app for recycling pickup scheduling.',
                'cost_benefit_analysis' => 'Improves recycling rates.',
                'declaration_of_interests' => 'None',
                'original_idea_disclaimer' => true,
                'collaboration_enabled' => true,
                'team_effort' => true,
                'current_revision_number' => 2,
                'collaboration_deadline' => now()->addWeeks(2),
                'status' => 'draft',
                'attachment' => null,
                'attachment_filename' => null,
                'attachment_mime' => null,
                'attachment_size' => null,
                'user_id' => rand(1, 5),
            ],
            [
                'idea_title' => 'AI-Powered Health Monitor',
                'slug' => Str::slug('AI-Powered Health Monitor-' . Str::random(4)),
                'thematic_area_id' => 1,
                'abstract' => 'Wearable device for continuous health monitoring.',
                'problem_statement' => 'Delayed detection of health issues.',
                'proposed_solution' => 'AI-driven wearable for early warning signs.',
                'cost_benefit_analysis' => 'Reduces healthcare costs through prevention.',
                'declaration_of_interests' => 'None',
                'original_idea_disclaimer' => true,
                'collaboration_enabled' => true,
                'team_effort' => true,
                'current_revision_number' => 1,
                'collaboration_deadline' => now()->addDays(30),
                'status' => 'stage 1 review',
                'attachment' => null,
                'attachment_filename' => null,
                'attachment_mime' => null,
                'attachment_size' => null,
                'user_id' => rand(1, 5),
            ],
            [
                'idea_title' => 'Urban Farming Pods',
                'slug' => Str::slug('Urban Farming Pods-' . Str::random(4)),
                'thematic_area_id' => 4,
                'abstract' => 'Automated farming systems for city environments.',
                'problem_statement' => 'Food security in urban areas.',
                'proposed_solution' => 'Vertical farming pods in buildings.',
                'cost_benefit_analysis' => 'Local food production, reduced transport costs.',
                'declaration_of_interests' => 'None',
                'original_idea_disclaimer' => false,
                'collaboration_enabled' => true,
                'team_effort' => false,
                'current_revision_number' => 1,
                'collaboration_deadline' => now()->addDays(45),
                'status' => 'draft',
                'attachment' => null,
                'attachment_filename' => null,
                'attachment_mime' => null,
                'attachment_size' => null,
                'user_id' => rand(1, 5),
            ],
            [
                'idea_title' => 'Digital Education Platform',
                'slug' => Str::slug('Digital Education Platform-' . Str::random(4)),
                'thematic_area_id' => 3,
                'abstract' => 'Interactive learning platform for remote education.',
                'problem_statement' => 'Unequal access to quality education.',
                'proposed_solution' => 'AI-powered personalized learning paths.',
                'cost_benefit_analysis' => 'Improves learning outcomes, reduces costs.',
                'declaration_of_interests' => 'None',
                'original_idea_disclaimer' => true,
                'collaboration_enabled' => false,
                'team_effort' => true,
                'current_revision_number' => 3,
                'collaboration_deadline' => null,
                'status' => 'approved',
                'attachment' => null,
                'attachment_filename' => null,
                'attachment_mime' => null,
                'attachment_size' => null,
                'user_id' => rand(1, 5),
            ],
            [
                'idea_title' => 'Smart Traffic Management',
                'slug' => Str::slug('Smart Traffic Management-' . Str::random(4)),
                'thematic_area_id' => 1,
                'abstract' => 'AI system for optimizing city traffic flow.',
                'problem_statement' => 'Traffic congestion in urban areas.',
                'proposed_solution' => 'Predictive traffic light control.',
                'cost_benefit_analysis' => 'Reduces travel time, lowers emissions.',
                'declaration_of_interests' => 'None',
                'original_idea_disclaimer' => true,
                'collaboration_enabled' => true,
                'team_effort' => true,
                'current_revision_number' => 2,
                'collaboration_deadline' => now()->addDays(60),
                'status' => 'stage 2 review',
                'attachment' => null,
                'attachment_filename' => null,
                'attachment_mime' => null,
                'attachment_size' => null,
                'user_id' => rand(1, 5),
            ],
            [
                'idea_title' => 'Waste-to-Energy Converter',
                'slug' => Str::slug('Waste-to-Energy Converter-' . Str::random(4)),
                'thematic_area_id' => 4,
                'abstract' => 'Device to convert organic waste into electricity.',
                'problem_statement' => 'Waste management and energy production.',
                'proposed_solution' => 'Micro-scale waste-to-energy systems.',
                'cost_benefit_analysis' => 'Reduces landfill waste, generates clean energy.',
                'declaration_of_interests' => 'None',
                'original_idea_disclaimer' => false,
                'collaboration_enabled' => true,
                'team_effort' => false,
                'current_revision_number' => 1,
                'collaboration_deadline' => now()->addDays(90),
                'status' => 'draft',
                'attachment' => null,
                'attachment_filename' => null,
                'attachment_mime' => null,
                'attachment_size' => null,
                'user_id' => rand(1, 5),
            ],
            [
                'idea_title' => 'Mental Health Companion App',
                'slug' => Str::slug('Mental Health Companion App-' . Str::random(4)),
                'thematic_area_id' => 2,
                'abstract' => 'AI-powered mental health support application.',
                'problem_statement' => 'Limited access to mental health services.',
                'proposed_solution' => '24/7 AI companion with professional integration.',
                'cost_benefit_analysis' => 'Improves mental health outcomes, reduces costs.',
                'declaration_of_interests' => 'None',
                'original_idea_disclaimer' => true,
                'collaboration_enabled' => false,
                'team_effort' => true,
                'current_revision_number' => 1,
                'collaboration_deadline' => null,
                'status' => 'stage 1 review',
                'attachment' => null,
                'attachment_filename' => null,
                'attachment_mime' => null,
                'attachment_size' => null,
                'user_id' => rand(1, 5),
            ],
            [
                'idea_title' => 'Blockchain Voting System',
                'slug' => Str::slug('Blockchain Voting System-' . Str::random(4)),
                'thematic_area_id' => 1,
                'abstract' => 'Secure and transparent voting platform.',
                'problem_statement' => 'Election security and voter confidence.',
                'proposed_solution' => 'Blockchain-based voting with privacy.',
                'cost_benefit_analysis' => 'Increases trust in democratic processes.',
                'declaration_of_interests' => 'None',
                'original_idea_disclaimer' => true,
                'collaboration_enabled' => true,
                'team_effort' => true,
                'current_revision_number' => 2,
                'collaboration_deadline' => now()->addDays(120),
                'status' => 'draft',
                'attachment' => null,
                'attachment_filename' => null,
                'attachment_mime' => null,
                'attachment_size' => null,
                'user_id' => rand(1, 5),
            ],
            [
                'idea_title' => 'Ocean Plastic Collector',
                'slug' => Str::slug('Ocean Plastic Collector-' . Str::random(4)),
                'thematic_area_id' => 4,
                'abstract' => 'Autonomous device for collecting ocean plastic.',
                'problem_statement' => 'Plastic pollution in oceans.',
                'proposed_solution' => 'Solar-powered floating collectors.',
                'cost_benefit_analysis' => 'Reduces marine pollution, creates economic value.',
                'declaration_of_interests' => 'None',
                'original_idea_disclaimer' => false,
                'collaboration_enabled' => true,
                'team_effort' => false,
                'current_revision_number' => 1,
                'collaboration_deadline' => now()->addDays(75),
                'status' => 'approved',
                'attachment' => null,
                'attachment_filename' => null,
                'attachment_mime' => null,
                'attachment_size' => null,
                'user_id' => rand(1, 5),
            ],
            [
                'idea_title' => 'Virtual Reality Education',
                'slug' => Str::slug('Virtual Reality Education-' . Str::random(4)),
                'thematic_area_id' => 3,
                'abstract' => 'VR classrooms for immersive learning experiences.',
                'problem_statement' => 'Engagement in traditional education.',
                'proposed_solution' => 'VR environments for interactive learning.',
                'cost_benefit_analysis' => 'Improves learning retention and engagement.',
                'declaration_of_interests' => 'None',
                'original_idea_disclaimer' => true,
                'collaboration_enabled' => false,
                'team_effort' => true,
                'current_revision_number' => 1,
                'collaboration_deadline' => null,
                'status' => 'draft',
                'attachment' => null,
                'attachment_filename' => null,
                'attachment_mime' => null,
                'attachment_size' => null,
                'user_id' => rand(1, 5),
            ],
            [
                'idea_title' => 'Smart Grid Energy System',
                'slug' => Str::slug('Smart Grid Energy System-' . Str::random(4)),
                'thematic_area_id' => 1,
                'abstract' => 'AI-managed electricity distribution network.',
                'problem_statement' => 'Inefficient energy distribution.',
                'proposed_solution' => 'Smart grid with predictive maintenance.',
                'cost_benefit_analysis' => 'Reduces outages, optimizes energy use.',
                'declaration_of_interests' => 'None',
                'original_idea_disclaimer' => true,
                'collaboration_enabled' => true,
                'team_effort' => true,
                'current_revision_number' => 3,
                'collaboration_deadline' => now()->addDays(100),
                'status' => 'stage 2 review',
                'attachment' => null,
                'attachment_filename' => null,
                'attachment_mime' => null,
                'attachment_size' => null,
                'user_id' => rand(1, 5),
            ],
            [
                'idea_title' => 'Agricultural Drone Network',
                'slug' => Str::slug('Agricultural Drone Network-' . Str::random(4)),
                'thematic_area_id' => 4,
                'abstract' => 'Drone system for precision farming.',
                'problem_statement' => 'Inefficient farming practices.',
                'proposed_solution' => 'AI drones for crop monitoring and treatment.',
                'cost_benefit_analysis' => 'Increases yield, reduces chemical use.',
                'declaration_of_interests' => 'None',
                'original_idea_disclaimer' => false,
                'collaboration_enabled' => true,
                'team_effort' => false,
                'current_revision_number' => 1,
                'collaboration_deadline' => now()->addDays(50),
                'status' => 'stage 1 review',
                'attachment' => null,
                'attachment_filename' => null,
                'attachment_mime' => null,
                'attachment_size' => null,
                'user_id' => rand(1, 5),
            ],
            [
                'idea_title' => 'Telemedicine Platform',
                'slug' => Str::slug('Telemedicine Platform-' . Str::random(4)),
                'thematic_area_id' => 2,
                'abstract' => 'Remote healthcare delivery system.',
                'problem_statement' => 'Limited healthcare access in remote areas.',
                'proposed_solution' => 'Integrated telemedicine with AI diagnostics.',
                'cost_benefit_analysis' => 'Improves healthcare access, reduces costs.',
                'declaration_of_interests' => 'None',
                'original_idea_disclaimer' => true,
                'collaboration_enabled' => false,
                'team_effort' => true,
                'current_revision_number' => 2,
                'collaboration_deadline' => null,
                'status' => 'approved',
                'attachment' => null,
                'attachment_filename' => null,
                'attachment_mime' => null,
                'attachment_size' => null,
                'user_id' => rand(1, 5),
            ],
            [
                'idea_title' => 'Carbon Capture Technology',
                'slug' => Str::slug('Carbon Capture Technology-' . Str::random(4)),
                'thematic_area_id' => 4,
                'abstract' => 'Direct air capture of CO2.',
                'problem_statement' => 'Climate change from CO2 emissions.',
                'proposed_solution' => 'Scalable carbon capture systems.',
                'cost_benefit_analysis' => 'Reduces atmospheric CO2, creates carbon credits.',
                'declaration_of_interests' => 'None',
                'original_idea_disclaimer' => true,
                'collaboration_enabled' => true,
                'team_effort' => true,
                'current_revision_number' => 1,
                'collaboration_deadline' => now()->addDays(180),
                'status' => 'draft',
                'attachment' => null,
                'attachment_filename' => null,
                'attachment_mime' => null,
                'attachment_size' => null,
                'user_id' => rand(1, 5),
            ],
            [
                'idea_title' => 'Language Learning AI',
                'slug' => Str::slug('Language Learning AI-' . Str::random(4)),
                'thematic_area_id' => 3,
                'abstract' => 'AI-powered language acquisition platform.',
                'problem_statement' => 'Ineffective language learning methods.',
                'proposed_solution' => 'Personalized AI language tutor.',
                'cost_benefit_analysis' => 'Accelerates language learning, reduces costs.',
                'declaration_of_interests' => 'None',
                'original_idea_disclaimer' => false,
                'collaboration_enabled' => false,
                'team_effort' => false,
                'current_revision_number' => 1,
                'collaboration_deadline' => null,
                'status' => 'stage 1 review',
                'attachment' => null,
                'attachment_filename' => null,
                'attachment_mime' => null,
                'attachment_size' => null,
                'user_id' => rand(1, 5),
            ],
            [
                'idea_title' => 'Autonomous Delivery Robots',
                'slug' => Str::slug('Autonomous Delivery Robots-' . Str::random(4)),
                'thematic_area_id' => 1,
                'abstract' => 'Robots for last-mile delivery.',
                'problem_statement' => 'Delivery inefficiencies and costs.',
                'proposed_solution' => 'AI-powered delivery robots.',
                'cost_benefit_analysis' => 'Reduces delivery costs, improves speed.',
                'declaration_of_interests' => 'None',
                'original_idea_disclaimer' => true,
                'collaboration_enabled' => true,
                'team_effort' => true,
                'current_revision_number' => 2,
                'collaboration_deadline' => now()->addDays(80),
                'status' => 'draft',
                'attachment' => null,
                'attachment_filename' => null,
                'attachment_mime' => null,
                'attachment_size' => null,
                'user_id' => rand(1, 5),
            ],
            [
                'idea_title' => 'Water Purification System',
                'slug' => Str::slug('Water Purification System-' . Str::random(4)),
                'thematic_area_id' => 4,
                'abstract' => 'Portable water purification for communities.',
                'problem_statement' => 'Clean water access in developing areas.',
                'proposed_solution' => 'Solar-powered purification units.',
                'cost_benefit_analysis' => 'Provides clean water, prevents diseases.',
                'declaration_of_interests' => 'None',
                'original_idea_disclaimer' => false,
                'collaboration_enabled' => true,
                'team_effort' => false,
                'current_revision_number' => 1,
                'collaboration_deadline' => now()->addDays(40),
                'status' => 'approved',
                'attachment' => null,
                'attachment_filename' => null,
                'attachment_mime' => null,
                'attachment_size' => null,
                'user_id' => rand(1, 5),
            ],
            [
                'idea_title' => 'AI Ethics Framework',
                'slug' => Str::slug('AI Ethics Framework-' . Str::random(4)),
                'thematic_area_id' => 1,
                'abstract' => 'Framework for ethical AI development.',
                'problem_statement' => 'Bias and ethical concerns in AI.',
                'proposed_solution' => 'Comprehensive AI ethics guidelines.',
                'cost_benefit_analysis' => 'Builds trust in AI systems.',
                'declaration_of_interests' => 'None',
                'original_idea_disclaimer' => true,
                'collaboration_enabled' => false,
                'team_effort' => true,
                'current_revision_number' => 1,
                'collaboration_deadline' => null,
                'status' => 'stage 2 review',
                'attachment' => null,
                'attachment_filename' => null,
                'attachment_mime' => null,
                'attachment_size' => null,
                'user_id' => rand(1, 5),
            ],
            [
                'idea_title' => 'Urban Green Spaces',
                'slug' => Str::slug('Urban Green Spaces-' . Str::random(4)),
                'thematic_area_id' => 4,
                'abstract' => 'Modular green installations for cities.',
                'problem_statement' => 'Lack of green spaces in urban areas.',
                'proposed_solution' => 'Vertical gardens and rooftop farms.',
                'cost_benefit_analysis' => 'Improves air quality, mental health.',
                'declaration_of_interests' => 'None',
                'original_idea_disclaimer' => true,
                'collaboration_enabled' => true,
                'team_effort' => false,
                'current_revision_number' => 2,
                'collaboration_deadline' => now()->addDays(65),
                'status' => 'draft',
                'attachment' => null,
                'attachment_filename' => null,
                'attachment_mime' => null,
                'attachment_size' => null,
                'user_id' => rand(1, 5),
            ],
            [
                'idea_title' => 'Personal Finance AI',
                'slug' => Str::slug('Personal Finance AI-' . Str::random(4)),
                'thematic_area_id' => 5,
                'abstract' => 'AI advisor for personal financial management.',
                'problem_statement' => 'Financial literacy and planning.',
                'proposed_solution' => 'AI-powered financial planning assistant.',
                'cost_benefit_analysis' => 'Improves financial outcomes.',
                'declaration_of_interests' => 'None',
                'original_idea_disclaimer' => false,
                'collaboration_enabled' => false,
                'team_effort' => false,
                'current_revision_number' => 1,
                'collaboration_deadline' => null,
                'status' => 'stage 1 review',
                'attachment' => null,
                'attachment_filename' => null,
                'attachment_mime' => null,
                'attachment_size' => null,
                'user_id' => rand(1, 5),
            ],
            [
                'idea_title' => 'Quantum Computing Education',
                'slug' => Str::slug('Quantum Computing Education-' . Str::random(4)),
                'thematic_area_id' => 3,
                'abstract' => 'Educational platform for quantum computing.',
                'problem_statement' => 'Quantum computing skills gap.',
                'proposed_solution' => 'Interactive quantum computing curriculum.',
                'cost_benefit_analysis' => 'Builds quantum workforce.',
                'declaration_of_interests' => 'None',
                'original_idea_disclaimer' => true,
                'collaboration_enabled' => true,
                'team_effort' => true,
                'current_revision_number' => 1,
                'collaboration_deadline' => now()->addDays(150),
                'status' => 'draft',
                'attachment' => null,
                'attachment_filename' => null,
                'attachment_mime' => null,
                'attachment_size' => null,
                'user_id' => rand(1, 5),
            ],
            [
                'idea_title' => 'Biodegradable Packaging',
                'slug' => Str::slug('Biodegradable Packaging-' . Str::random(4)),
                'thematic_area_id' => 4,
                'abstract' => 'Sustainable packaging alternatives.',
                'problem_statement' => 'Plastic pollution from packaging.',
                'proposed_solution' => 'Mushroom-based biodegradable packaging.',
                'cost_benefit_analysis' => 'Reduces plastic waste, creates jobs.',
                'declaration_of_interests' => 'None',
                'original_idea_disclaimer' => false,
                'collaboration_enabled' => true,
                'team_effort' => false,
                'current_revision_number' => 1,
                'collaboration_deadline' => now()->addDays(55),
                'status' => 'approved',
                'attachment' => null,
                'attachment_filename' => null,
                'attachment_mime' => null,
                'attachment_size' => null,
                'user_id' => rand(1, 5),
            ],
            [
                'idea_title' => 'Remote Surgery Technology',
                'slug' => Str::slug('Remote Surgery Technology-' . Str::random(4)),
                'thematic_area_id' => 2,
                'abstract' => 'Haptic feedback system for remote surgery.',
                'problem_statement' => 'Surgical access in remote areas.',
                'proposed_solution' => 'Tele-surgery with haptic feedback.',
                'cost_benefit_analysis' => 'Expands surgical care access.',
                'declaration_of_interests' => 'None',
                'original_idea_disclaimer' => true,
                'collaboration_enabled' => false,
                'team_effort' => true,
                'current_revision_number' => 2,
                'collaboration_deadline' => null,
                'status' => 'stage 2 review',
                'attachment' => null,
                'attachment_filename' => null,
                'attachment_mime' => null,
                'attachment_size' => null,
                'user_id' => rand(1, 5),
            ],
            [
                'idea_title' => 'Climate Prediction AI',
                'slug' => Str::slug('Climate Prediction AI-' . Str::random(4)),
                'thematic_area_id' => 4,
                'abstract' => 'Advanced climate modeling and prediction.',
                'problem_statement' => 'Inaccurate climate predictions.',
                'proposed_solution' => 'AI-enhanced climate models.',
                'cost_benefit_analysis' => 'Better disaster preparedness.',
                'declaration_of_interests' => 'None',
                'original_idea_disclaimer' => true,
                'collaboration_enabled' => true,
                'team_effort' => true,
                'current_revision_number' => 3,
                'collaboration_deadline' => now()->addDays(200),
                'status' => 'draft',
                'attachment' => null,
                'attachment_filename' => null,
                'attachment_mime' => null,
                'attachment_size' => null,
                'user_id' => rand(1, 5),
            ],
            [
                'idea_title' => 'Digital Twin Cities',
                'slug' => Str::slug('Digital Twin Cities-' . Str::random(4)),
                'thematic_area_id' => 1,
                'abstract' => 'Virtual replicas of cities for planning.',
                'problem_statement' => 'Inefficient urban planning.',
                'proposed_solution' => 'Digital twins for city simulation.',
                'cost_benefit_analysis' => 'Optimizes city planning, reduces costs.',
                'declaration_of_interests' => 'None',
                'original_idea_disclaimer' => false,
                'collaboration_enabled' => true,
                'team_effort' => false,
                'current_revision_number' => 1,
                'collaboration_deadline' => now()->addDays(90),
                'status' => 'stage 1 review',
                'attachment' => null,
                'attachment_filename' => null,
                'attachment_mime' => null,
                'attachment_size' => null,
                'user_id' => rand(1, 5),
            ],
            [
                'idea_title' => 'Microbiome Health Tests',
                'slug' => Str::slug('Microbiome Health Tests-' . Str::random(4)),
                'thematic_area_id' => 2,
                'abstract' => 'Home microbiome testing kits.',
                'problem_statement' => 'Limited gut health monitoring.',
                'proposed_solution' => 'Affordable microbiome analysis.',
                'cost_benefit_analysis' => 'Enables preventive health measures.',
                'declaration_of_interests' => 'None',
                'original_idea_disclaimer' => true,
                'collaboration_enabled' => false,
                'team_effort' => true,
                'current_revision_number' => 1,
                'collaboration_deadline' => null,
                'status' => 'approved',
                'attachment' => null,
                'attachment_filename' => null,
                'attachment_mime' => null,
                'attachment_size' => null,
                'user_id' => rand(1, 5),
            ],
            [
                'idea_title' => 'Satellite Internet Constellation',
                'slug' => Str::slug('Satellite Internet Constellation-' . Str::random(4)),
                'thematic_area_id' => 1,
                'abstract' => 'Low-orbit satellite internet network.',
                'problem_statement' => 'Internet access in remote areas.',
                'proposed_solution' => 'Global satellite internet coverage.',
                'cost_benefit_analysis' => 'Bridges digital divide.',
                'declaration_of_interests' => 'None',
                'original_idea_disclaimer' => true,
                'collaboration_enabled' => true,
                'team_effort' => true,
                'current_revision_number' => 2,
                'collaboration_deadline' => now()->addDays(300),
                'status' => 'draft',
                'attachment' => null,
                'attachment_filename' => null,
                'attachment_mime' => null,
                'attachment_size' => null,
                'user_id' => rand(1, 5),
            ],
            [
                'idea_title' => 'AI Art Generator',
                'slug' => Str::slug('AI Art Generator-' . Str::random(4)),
                'thematic_area_id' => 3,
                'abstract' => 'Creative AI for artistic expression.',
                'problem_statement' => 'Limited artistic tools for beginners.',
                'proposed_solution' => 'AI-powered art creation platform.',
                'cost_benefit_analysis' => 'Democratizes art creation.',
                'declaration_of_interests' => 'None',
                'original_idea_disclaimer' => false,
                'collaboration_enabled' => false,
                'team_effort' => false,
                'current_revision_number' => 1,
                'collaboration_deadline' => null,
                'status' => 'stage 1 review',
                'attachment' => null,
                'attachment_filename' => null,
                'attachment_mime' => null,
                'attachment_size' => null,
                'user_id' => rand(1, 5),
            ],
            [
                'idea_title' => 'Vertical Wind Turbines',
                'slug' => Str::slug('Vertical Wind Turbines-' . Str::random(4)),
                'thematic_area_id' => 4,
                'abstract' => 'Urban-friendly wind energy generation.',
                'problem_statement' => 'Wind energy in urban environments.',
                'proposed_solution' => 'Vertical axis wind turbines for cities.',
                'cost_benefit_analysis' => 'Clean energy in urban settings.',
                'declaration_of_interests' => 'None',
                'original_idea_disclaimer' => true,
                'collaboration_enabled' => true,
                'team_effort' => false,
                'current_revision_number' => 1,
                'collaboration_deadline' => now()->addDays(70),
                'status' => 'approved',
                'attachment' => null,
                'attachment_filename' => null,
                'attachment_mime' => null,
                'attachment_size' => null,
                'user_id' => rand(1, 5),
            ],
            [
                'idea_title' => 'Blockchain Supply Chain',
                'slug' => Str::slug('Blockchain Supply Chain-' . Str::random(4)),
                'thematic_area_id' => 5,
                'abstract' => 'Transparent supply chain tracking.',
                'problem_statement' => 'Supply chain opacity and fraud.',
                'proposed_solution' => 'Blockchain-based supply chain visibility.',
                'cost_benefit_analysis' => 'Reduces fraud, improves efficiency.',
                'declaration_of_interests' => 'None',
                'original_idea_disclaimer' => false,
                'collaboration_enabled' => true,
                'team_effort' => true,
                'current_revision_number' => 2,
                'collaboration_deadline' => now()->addDays(110),
                'status' => 'stage 2 review',
                'attachment' => null,
                'attachment_filename' => null,
                'attachment_mime' => null,
                'attachment_size' => null,
                'user_id' => rand(1, 5),
            ],
            [
                'idea_title' => 'Gamified Learning Platform',
                'slug' => Str::slug('Gamified Learning Platform-' . Str::random(4)),
                'thematic_area_id' => 3,
                'abstract' => 'Game-based education system.',
                'problem_statement' => 'Student engagement in learning.',
                'proposed_solution' => 'Gamified curriculum delivery.',
                'cost_benefit_analysis' => 'Improves learning outcomes.',
                'declaration_of_interests' => 'None',
                'original_idea_disclaimer' => true,
                'collaboration_enabled' => false,
                'team_effort' => true,
                'current_revision_number' => 1,
                'collaboration_deadline' => null,
                'status' => 'draft',
                'attachment' => null,
                'attachment_filename' => null,
                'attachment_mime' => null,
                'attachment_size' => null,
                'user_id' => rand(1, 5),
            ],
            [
                'idea_title' => 'Nanotech Water Filters',
                'slug' => Str::slug('Nanotech Water Filters-' . Str::random(4)),
                'thematic_area_id' => 4,
                'abstract' => 'Advanced water filtration technology.',
                'problem_statement' => 'Water contamination issues.',
                'proposed_solution' => 'Nanotechnology-based water filters.',
                'cost_benefit_analysis' => 'Provides clean water affordably.',
                'declaration_of_interests' => 'None',
                'original_idea_disclaimer' => true,
                'collaboration_enabled' => true,
                'team_effort' => false,
                'current_revision_number' => 1,
                'collaboration_deadline' => now()->addDays(85),
                'status' => 'stage 1 review',
                'attachment' => null,
                'attachment_filename' => null,
                'attachment_mime' => null,
                'attachment_size' => null,
                'user_id' => rand(1, 5),
            ],
            [
                'idea_title' => 'AI Legal Assistant',
                'slug' => Str::slug('AI Legal Assistant-' . Str::random(4)),
                'thematic_area_id' => 5,
                'abstract' => 'AI-powered legal document analysis.',
                'problem_statement' => 'Legal document complexity.',
                'proposed_solution' => 'AI assistant for legal research.',
                'cost_benefit_analysis' => 'Reduces legal costs, improves access.',
                'declaration_of_interests' => 'None',
                'original_idea_disclaimer' => false,
                'collaboration_enabled' => false,
                'team_effort' => true,
                'current_revision_number' => 2,
                'collaboration_deadline' => null,
                'status' => 'approved',
                'attachment' => null,
                'attachment_filename' => null,
                'attachment_mime' => null,
                'attachment_size' => null,
                'user_id' => rand(1, 5),
            ],
            [
                'idea_title' => 'Holographic Communication',
                'slug' => Str::slug('Holographic Communication-' . Str::random(4)),
                'thematic_area_id' => 1,
                'abstract' => '3D holographic video calling.',
                'problem_statement' => 'Limited remote presence technology.',
                'proposed_solution' => 'Holographic communication devices.',
                'cost_benefit_analysis' => 'Enhances remote collaboration.',
                'declaration_of_interests' => 'None',
                'original_idea_disclaimer' => true,
                'collaboration_enabled' => true,
                'team_effort' => true,
                'current_revision_number' => 1,
                'collaboration_deadline' => now()->addDays(160),
                'status' => 'draft',
                'attachment' => null,
                'attachment_filename' => null,
                'attachment_mime' => null,
                'attachment_size' => null,
                'user_id' => rand(1, 5),
            ],
            [
                'idea_title' => 'Personalized Nutrition AI',
                'slug' => Str::slug('Personalized Nutrition AI-' . Str::random(4)),
                'thematic_area_id' => 2,
                'abstract' => 'AI-driven nutrition planning.',
                'problem_statement' => 'Ineffective diet planning.',
                'proposed_solution' => 'Personalized nutrition recommendations.',
                'cost_benefit_analysis' => 'Improves health outcomes.',
                'declaration_of_interests' => 'None',
                'original_idea_disclaimer' => false,
                'collaboration_enabled' => false,
                'team_effort' => false,
                'current_revision_number' => 1,
                'collaboration_deadline' => null,
                'status' => 'stage 2 review',
                'attachment' => null,
                'attachment_filename' => null,
                'attachment_mime' => null,
                'attachment_size' => null,
                'user_id' => rand(1, 5),
            ],
            [
                'idea_title' => 'Smart City Sensors',
                'slug' => Str::slug('Smart City Sensors-' . Str::random(4)),
                'thematic_area_id' => 1,
                'abstract' => 'IoT sensors for city infrastructure monitoring.',
                'problem_statement' => 'City infrastructure maintenance.',
                'proposed_solution' => 'Predictive maintenance sensors.',
                'cost_benefit_analysis' => 'Reduces maintenance costs, improves safety.',
                'declaration_of_interests' => 'None',
                'original_idea_disclaimer' => true,
                'collaboration_enabled' => true,
                'team_effort' => false,
                'current_revision_number' => 2,
                'collaboration_deadline' => now()->addDays(95),
                'status' => 'stage 1 review',
                'attachment' => null,
                'attachment_filename' => null,
                'attachment_mime' => null,
                'attachment_size' => null,
                'user_id' => rand(1, 5),
            ],
            [
                'idea_title' => 'Regenerative Agriculture Tech',
                'slug' => Str::slug('Regenerative Agriculture Tech-' . Str::random(4)),
                'thematic_area_id' => 4,
                'abstract' => 'Technology for soil regeneration.',
                'problem_statement' => 'Soil degradation from farming.',
                'proposed_solution' => 'Regenerative farming monitoring tools.',
                'cost_benefit_analysis' => 'Restores soil health, increases yields.',
                'declaration_of_interests' => 'None',
                'original_idea_disclaimer' => true,
                'collaboration_enabled' => true,
                'team_effort' => true,
                'current_revision_number' => 1,
                'collaboration_deadline' => now()->addDays(130),
                'status' => 'draft',
                'attachment' => null,
                'attachment_filename' => null,
                'attachment_mime' => null,
                'attachment_size' => null,
                'user_id' => rand(1, 5),
            ],
            [
                'idea_title' => 'Quantum Encryption',
                'slug' => Str::slug('Quantum Encryption-' . Str::random(4)),
                'thematic_area_id' => 1,
                'abstract' => 'Unbreakable encryption using quantum principles.',
                'problem_statement' => 'Data security threats.',
                'proposed_solution' => 'Quantum key distribution systems.',
                'cost_benefit_analysis' => 'Provides ultimate data security.',
                'declaration_of_interests' => 'None',
                'original_idea_disclaimer' => false,
                'collaboration_enabled' => false,
                'team_effort' => true,
                'current_revision_number' => 1,
                'collaboration_deadline' => null,
                'status' => 'approved',
                'attachment' => null,
                'attachment_filename' => null,
                'attachment_mime' => null,
                'attachment_size' => null,
                'user_id' => rand(1, 5),
            ],
            [
                'idea_title' => 'Ocean Current Energy',
                'slug' => Str::slug('Ocean Current Energy-' . Str::random(4)),
                'thematic_area_id' => 4,
                'abstract' => 'Harnessing ocean currents for energy.',
                'problem_statement' => 'Renewable energy sources.',
                'proposed_solution' => 'Underwater turbines for current energy.',
                'cost_benefit_analysis' => 'Reliable renewable energy source.',
                'declaration_of_interests' => 'None',
                'original_idea_disclaimer' => true,
                'collaboration_enabled' => true,
                'team_effort' => false,
                'current_revision_number' => 2,
                'collaboration_deadline' => now()->addDays(250),
                'status' => 'stage 2 review',
                'attachment' => null,
                'attachment_filename' => null,
                'attachment_mime' => null,
                'attachment_size' => null,
                'user_id' => rand(1, 5),
            ],
            [
                'idea_title' => 'AI Music Composer',
                'slug' => Str::slug('AI Music Composer-' . Str::random(4)),
                'thematic_area_id' => 3,
                'abstract' => 'AI system for music composition.',
                'problem_statement' => 'Creative blocks in music production.',
                'proposed_solution' => 'AI collaborative music creation.',
                'cost_benefit_analysis' => 'Accelerates music production.',
                'declaration_of_interests' => 'None',
                'original_idea_disclaimer' => false,
                'collaboration_enabled' => false,
                'team_effort' => false,
                'current_revision_number' => 1,
                'collaboration_deadline' => null,
                'status' => 'draft',
                'attachment' => null,
                'attachment_filename' => null,
                'attachment_mime' => null,
                'attachment_size' => null,
                'user_id' => rand(1, 5),
            ],
            [
                'idea_title' => 'Biofuel from Algae',
                'slug' => Str::slug('Biofuel from Algae-' . Str::random(4)),
                'thematic_area_id' => 4,
                'abstract' => 'Algae-based biofuel production.',
                'problem_statement' => 'Sustainable fuel alternatives.',
                'proposed_solution' => 'Large-scale algae biofuel farms.',
                'cost_benefit_analysis' => 'Carbon-neutral fuel production.',
                'declaration_of_interests' => 'None',
                'original_idea_disclaimer' => true,
                'collaboration_enabled' => true,
                'team_effort' => true,
                'current_revision_number' => 1,
                'collaboration_deadline' => now()->addDays(140),
                'status' => 'stage 1 review',
                'attachment' => null,
                'attachment_filename' => null,
                'attachment_mime' => null,
                'attachment_size' => null,
                'user_id' => rand(1, 5),
            ],
            [
                'idea_title' => 'Neural Interface Education',
                'slug' => Str::slug('Neural Interface Education-' . Str::random(4)),
                'thematic_area_id' => 3,
                'abstract' => 'Brain-computer interfaces for learning.',
                'problem_statement' => 'Learning speed limitations.',
                'proposed_solution' => 'Direct knowledge transfer interfaces.',
                'cost_benefit_analysis' => 'Revolutionary learning acceleration.',
                'declaration_of_interests' => 'None',
                'original_idea_disclaimer' => true,
                'collaboration_enabled' => false,
                'team_effort' => true,
                'current_revision_number' => 1,
                'collaboration_deadline' => null,
                'status' => 'draft',
                'attachment' => null,
                'attachment_filename' => null,
                'attachment_mime' => null,
                'attachment_size' => null,
                'user_id' => rand(1, 5),
            ],
            [
                'idea_title' => 'Space Debris Cleanup',
                'slug' => Str::slug('Space Debris Cleanup-' . Str::random(4)),
                'thematic_area_id' => 1,
                'abstract' => 'Technology to remove space debris.',
                'problem_statement' => 'Space debris threatening satellites.',
                'proposed_solution' => 'Autonomous debris collection satellites.',
                'cost_benefit_analysis' => 'Ensures space sustainability.',
                'declaration_of_interests' => 'None',
                'original_idea_disclaimer' => false,
                'collaboration_enabled' => true,
                'team_effort' => false,
                'current_revision_number' => 2,
                'collaboration_deadline' => now()->addDays(400),
                'status' => 'approved',
                'attachment' => null,
                'attachment_filename' => null,
                'attachment_mime' => null,
                'attachment_size' => null,
                'user_id' => rand(1, 5),
            ],
            [
                'idea_title' => 'Gene Therapy Delivery',
                'slug' => Str::slug('Gene Therapy Delivery-' . Str::random(4)),
                'thematic_area_id' => 2,
                'abstract' => 'Targeted gene therapy systems.',
                'problem_statement' => 'Ineffective gene therapy delivery.',
                'proposed_solution' => 'Nanoparticle gene delivery systems.',
                'cost_benefit_analysis' => 'Treats genetic diseases effectively.',
                'declaration_of_interests' => 'None',
                'original_idea_disclaimer' => true,
                'collaboration_enabled' => false,
                'team_effort' => true,
                'current_revision_number' => 1,
                'collaboration_deadline' => null,
                'status' => 'stage 2 review',
                'attachment' => null,
                'attachment_filename' => null,
                'attachment_mime' => null,
                'attachment_size' => null,
                'user_id' => rand(1, 5),
            ],
            [
                'idea_title' => 'Fusion Energy Research',
                'slug' => Str::slug('Fusion Energy Research-' . Str::random(4)),
                'thematic_area_id' => 4,
                'abstract' => 'Practical nuclear fusion power.',
                'problem_statement' => 'Sustainable energy production.',
                'proposed_solution' => 'Compact fusion reactors.',
                'cost_benefit_analysis' => 'Unlimited clean energy.',
                'declaration_of_interests' => 'None',
                'original_idea_disclaimer' => true,
                'collaboration_enabled' => true,
                'team_effort' => true,
                'current_revision_number' => 3,
                'collaboration_deadline' => now()->addDays(500),
                'status' => 'draft',
                'attachment' => null,
                'attachment_filename' => null,
                'attachment_mime' => null,
                'attachment_size' => null,
                'user_id' => rand(1, 5),
            ],
            [
                'idea_title' => 'Universal Language Translator',
                'slug' => Str::slug('Universal Language Translator-' . Str::random(4)),
                'thematic_area_id' => 3,
                'abstract' => 'Real-time universal language translation.',
                'problem_statement' => 'Language barriers in communication.',
                'proposed_solution' => 'AI-powered universal translator.',
                'cost_benefit_analysis' => 'Breaks down global communication barriers.',
                'declaration_of_interests' => 'None',
                'original_idea_disclaimer' => false,
                'collaboration_enabled' => false,
                'team_effort' => false,
                'current_revision_number' => 1,
                'collaboration_deadline' => null,
                'status' => 'stage 1 review',
                'attachment' => null,
                'attachment_filename' => null,
                'attachment_mime' => null,
                'attachment_size' => null,
                'user_id' => rand(1, 5),
            ],
            [
                'idea_title' => 'Cybersecurity AI',
                'slug' => Str::slug('Cybersecurity AI-' . Str::random(4)),
                'thematic_area_id' => 1,
                'abstract' => 'AI systems for threat detection.',
                'problem_statement' => 'Increasing cyber threats.',
                'proposed_solution' => 'Predictive cybersecurity AI.',
                'cost_benefit_analysis' => 'Prevents cyber attacks proactively.',
                'declaration_of_interests' => 'None',
                'original_idea_disclaimer' => true,
                'collaboration_enabled' => true,
                'team_effort' => false,
                'current_revision_number' => 2,
                'collaboration_deadline' => now()->addDays(75),
                'status' => 'approved',
                'attachment' => null,
                'attachment_filename' => null,
                'attachment_mime' => null,
                'attachment_size' => null,
                'user_id' => rand(1, 5),
            ],
            [
                'idea_title' => 'Lab-Grown Meat Technology',
                'slug' => Str::slug('Lab-Grown Meat Technology-' . Str::random(4)),
                'thematic_area_id' => 4,
                'abstract' => 'Cultured meat production systems.',
                'problem_statement' => 'Environmental impact of meat production.',
                'proposed_solution' => 'Sustainable lab-grown meat.',
                'cost_benefit_analysis' => 'Reduces environmental impact of food.',
                'declaration_of_interests' => 'None',
                'original_idea_disclaimer' => false,
                'collaboration_enabled' => true,
                'team_effort' => true,
                'current_revision_number' => 1,
                'collaboration_deadline' => now()->addDays(180),
                'status' => 'stage 2 review',
                'attachment' => null,
                'attachment_filename' => null,
                'attachment_mime' => null,
                'attachment_size' => null,
                'user_id' => rand(1, 5),
            ],
            [
                'idea_title' => 'Emotion Recognition AI',
                'slug' => Str::slug('Emotion Recognition AI-' . Str::random(4)),
                'thematic_area_id' => 2,
                'abstract' => 'AI for emotional intelligence assessment.',
                'problem_statement' => 'Understanding human emotions.',
                'proposed_solution' => 'Real-time emotion recognition.',
                'cost_benefit_analysis' => 'Improves mental health diagnostics.',
                'declaration_of_interests' => 'None',
                'original_idea_disclaimer' => true,
                'collaboration_enabled' => false,
                'team_effort' => true,
                'current_revision_number' => 1,
                'collaboration_deadline' => null,
                'status' => 'draft',
                'attachment' => null,
                'attachment_filename' => null,
                'attachment_mime' => null,
                'attachment_size' => null,
                'user_id' => rand(1, 5),
            ],
            [
                'idea_title' => 'Autonomous Construction',
                'slug' => Str::slug('Autonomous Construction-' . Str::random(4)),
                'thematic_area_id' => 1,
                'abstract' => 'Robotic construction systems.',
                'problem_statement' => 'Construction industry inefficiencies.',
                'proposed_solution' => 'AI-controlled construction robots.',
                'cost_benefit_analysis' => 'Faster, safer, cheaper construction.',
                'declaration_of_interests' => 'None',
                'original_idea_disclaimer' => true,
                'collaboration_enabled' => true,
                'team_effort' => false,
                'current_revision_number' => 2,
                'collaboration_deadline' => now()->addDays(120),
                'status' => 'stage 1 review',
                'attachment' => null,
                'attachment_filename' => null,
                'attachment_mime' => null,
                'attachment_size' => null,
                'user_id' => rand(1, 5),
            ],
            [
                'idea_title' => 'Brain-Computer Gaming',
                'slug' => Str::slug('Brain-Computer Gaming-' . Str::random(4)),
                'thematic_area_id' => 3,
                'abstract' => 'Mind-controlled gaming experiences.',
                'problem_statement' => 'Traditional gaming limitations.',
                'proposed_solution' => 'BCI-powered immersive gaming.',
                'cost_benefit_analysis' => 'Revolutionary gaming experiences.',
                'declaration_of_interests' => 'None',
                'original_idea_disclaimer' => false,
                'collaboration_enabled' => false,
                'team_effort' => false,
                'current_revision_number' => 1,
                'collaboration_deadline' => null,
                'status' => 'approved',
                'attachment' => null,
                'attachment_filename' => null,
                'attachment_mime' => null,
                'attachment_size' => null,
                'user_id' => rand(1, 5),
            ],
            [
                'idea_title' => 'Weather Modification Tech',
                'slug' => Str::slug('Weather Modification Tech-' . Str::random(4)),
                'thematic_area_id' => 4,
                'abstract' => 'Controlled weather modification systems.',
                'problem_statement' => 'Extreme weather events.',
                'proposed_solution' => 'Cloud seeding and weather control.',
                'cost_benefit_analysis' => 'Mitigates climate disasters.',
                'declaration_of_interests' => 'None',
                'original_idea_disclaimer' => true,
                'collaboration_enabled' => true,
                'team_effort' => true,
                'current_revision_number' => 1,
                'collaboration_deadline' => now()->addDays(300),
                'status' => 'draft',
                'attachment' => null,
                'attachment_filename' => null,
                'attachment_mime' => null,
                'attachment_size' => null,
                'user_id' => rand(1, 5),
            ],
            [
                'idea_title' => 'Digital Identity Blockchain',
                'slug' => Str::slug('Digital Identity Blockchain-' . Str::random(4)),
                'thematic_area_id' => 5,
                'abstract' => 'Self-sovereign digital identity system.',
                'problem_statement' => 'Identity theft and privacy concerns.',
                'proposed_solution' => 'Blockchain-based digital identity.',
                'cost_benefit_analysis' => 'Secure, private digital identities.',
                'declaration_of_interests' => 'None',
                'original_idea_disclaimer' => false,
                'collaboration_enabled' => false,
                'team_effort' => true,
                'current_revision_number' => 2,
                'collaboration_deadline' => null,
                'status' => 'stage 2 review',
                'attachment' => null,
                'attachment_filename' => null,
                'attachment_mime' => null,
                'attachment_size' => null,
                'user_id' => rand(1, 5),
            ],
            [
                'idea_title' => 'Quantum Machine Learning',
                'slug' => Str::slug('Quantum Machine Learning-' . Str::random(4)),
                'thematic_area_id' => 1,
                'abstract' => 'Quantum algorithms for machine learning.',
                'problem_statement' => 'ML computational limitations.',
                'proposed_solution' => 'Quantum-enhanced ML algorithms.',
                'cost_benefit_analysis' => 'Revolutionary computational capabilities.',
                'declaration_of_interests' => 'None',
                'original_idea_disclaimer' => true,
                'collaboration_enabled' => true,
                'team_effort' => false,
                'current_revision_number' => 1,
                'collaboration_deadline' => now()->addDays(220),
                'status' => 'stage 1 review',
                'attachment' => null,
                'attachment_filename' => null,
                'attachment_mime' => null,
                'attachment_size' => null,
                'user_id' => rand(1, 5),
            ],
        ];

        foreach ($ideas as $idea) {
            Idea::create($idea);
        }
    }
}
